### ISSUE TITLE
Feature request - brands and menu options

### ISSUE THREAD

**Issue by ghost** [tiipiik/oc-catalog#1]
Hi,

We are using catalog now in multiple projects. We realy like the plugin. But whe have two things that we are missing. 
1. Managing brands
   - It would be nice if there was a brand section, where we can add and manage brands and connect to products the same way as groups. And have the option in the frontend to filter on brands for example.
2. Add categories / products links to the menu in static pages plugin. 
   - We would like to add some categories to our menu with the option to show nested categories in the menu or even direct products links without copy paste the url's of the pages in the menu. The same way as the blog plugin for example.

Are these 2 options something that you want and will to implement into the catalog plugin?

**Comment by tiipiik** [comment]
Hi,

Thanks for using this plugin :)

Yes it's something I can implement inside the plugin. I'll try to make this soon.

**Comment by ghost** [comment]
Thanks for your reply @tiipiik! We are looking forward to the new features :+1:

**Comment by tiipiik** [comment]
Hi @joris-vdlp,

I've just added support for Static Pages Menu plugin in the 1.7.0 version. Could you make some tests and tell me if everything is good ?

For now I've only added links to dynamic categories and targeted category.

This version is only available for edges updates.

If needed you can refer to the [documentation](http://octobercms-catalog.yohann-decharraud.com/how-it-works/catalog-static-page-menu/)

**Comment by ghost** [comment]
Thats quick @tiipiik :)

I will look into it (hopefully today) and if i find something i will let you know.

**Comment by tiipiik** [comment]
@joris-vdlp : You can now find Brands with related components, Stores enhanced and links to stores and brand in the product details component in v.1.8.0

And also have noticed a lot of ideas for improvements. I think I will started soon to work on version 2.

Please let me know if you have problems or if you want something else.
