### ISSUE TITLE
bad category selection

### ISSUE THREAD

**Issue by ASM-Development** [tiipiik/oc-catalog#10]
On product update checking one children category also wrongly checks another checkboxes

[sample](https://1.downloader.disk.yandex.ru/disk/c00b7dfd996f2073179cabda31702a6e0913f2bf468e85bf6d6de14c3ebc5541/57446309/UanJibg3kudbO3OMf3bLWHIksyfzHUymCTihdjzpUf7eqTBhE_Vu2XIeWsemN550AoZHsXzu2DQ9CPf6OrDgtg%3D%3D?uid=0&filename=2016-05-24_14-16-45.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=44076&hid=6dc692096787e820ddf90c54381a76ba&media_type=image&tknv=v2&etag=8b84044bacad3b60f56eee54dd7413fa)

**Comment by tiipiik** [comment]
Your sample is 404, but I think I understand. Things where going right until now, I'll check that
