### ISSUE TITLE
Pagination won't work

### ISSUE THREAD

**Issue by StrangerPings** [tiipiik/oc-catalog#12]
I have set up a products page but without checking the categories checkbox it won't display any products.  When I do get the products displaying the pagination calculates the correct amount per page and displays the numbers but for some reason when I click on a number it wont load those products.

The url displays as

`?page=2`

But it wont show the second page.  I also have /:page? in the uri so not sure why.  I've submitted a request on the [product support forum](https://octobercms.com/plugin/support/tiipiik-catalog/paignation-not-working-pn-products-page) Any help would be greatly appreciated :)

**Comment by StrangerPings** [comment]
Fixed the issue in this pull request.

#13 

issue being 

```
'page' => $this->property('pageParam'),
// needs to be set to 
'page' => $this->property('pageNumber'),
```

**Comment by tiipiik** [comment]
Thanks @StrangerPings for this good PR ;)
