### ISSUE TITLE
Secure URL's

### ISSUE THREAD

**Issue by ndcisiv** [tiipiik/oc-catalog#2]
When outputting a Product Details URL, it is defaulting to a secure URL.  The component shows the default to be false, but something is setting it to be true.  Under the CMS page, with the Product Details component added, under the settings for Links->Use secure urls, the checkbox is unchecked and it still uses them.  When checked it still uses them.  However if I click the '>_' link and manually type in 'false', un-secure URLs are used instead.  Since there is a checkbox, this seems very non-intuitive.

**Comment by tiipiik** [comment]
Last version should correct this bug.
