### ISSUE TITLE
Permalinks for product and category pages & meta tag references

### ISSUE THREAD

**Issue by heinvv** [tiipiik/oc-catalog#20]
We'd like to create the following url structure: 
- category pages: domain.com/product-category
- product pages: domain.com/product-category/product-name

Is this possible with your plugin?

I know it is possible for products to use the '/:slug' reference. Is there a similar reference for categories?

---

We'd like to display the meta tag information on the product page as well. 
Where can we find the references for the meta title & description?

**Comment by tiipiik** [comment]
This is possible yeah, please refer to the documentation [here](http://octobercms-catalog.yohann-decharraud.com/how-it-works/configuration/)

Metas are available for products, with dedicated fields for each product, but categories are generated from the category name and description. You can extedn the plugin to add more fields if you want.

**Comment by heinvv** [comment]
Thank you!

Where can we find the references for the meta tags? How can we include them in a page layout template?

**Comment by tiipiik** [comment]
This is an example of the meta tages management 
![capture d ecran 2018-02-16 a 14 08 09](https://user-images.githubusercontent.com/3844253/36308945-fb958fe2-1322-11e8-9a9c-c3ef5ae54040.png)

And this is how I use the meta in the layouts
```php
{% if this.page.meta_title %}
    <title>{{ this.page.meta_title|raw }}</title>
    <meta name="title" content="{{ this.page.meta_title|raw }}">
{% else %}
    <title>{{ this.page.title|raw }}</title>
{% endif %}
{% if this.page.meta_description %}
    <meta name="description" content="{{ this.page.meta_description }}">
{% elseif this.page.description %}
    <meta name="description" content="{{ this.page.description|raw }}">
{% endif %}
```

**Comment by heinvv** [comment]
Thank you so much

On 16 Feb 2018 15:13, "Yohann Decharraud" <notifications@github.com> wrote:

This is an example of the meta tages management
[image: capture d ecran 2018-02-16 a 14 08 09]
<https://user-images.githubusercontent.com/3844253/36308945-fb958fe2-1322-11e8-9a9c-c3ef5ae54040.png>

And this is how I use the meta in the layouts

{% if this.page.meta_title %}    <title>{{ this.page.meta_title|raw
}}</title>    <meta name="title" content="{{ this.page.meta_title|raw
}}">{% else %}    <title>{{ this.page.title|raw }}</title>{% endif
%}{% if this.page.meta_description %}    <meta name="description"
content="{{ this.page.meta_description }}">{% elseif
this.page.description %}    <meta name="description" content="{{
this.page.description|raw }}">{% endif %}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tiipiik/oc-catalog/issues/20#issuecomment-366231696>,
or mute the thread

**Comment by heinvv** [comment]
I'd like to build a customised category page as well. 
Is there a tutorial available about how to do that? 

I'd like to create a bootstrap grid list with title, image, and description.

**Comment by tiipiik** [comment]
You have informations about the category page [here](http://octobercms-catalog.yohann-decharraud.com/how-it-works/configuration/)
You can switch between the menu_list and image_list views, so you can display a bootstrap grid like you want with the image_view. You can also override (and I encourage you to do it as futur update can break your views), the default view so you can adapt it just like you want. [Here](https://octobercms.com/docs/cms/components#overriding-partials) is the corresponding documentation page for partials overriding.
