### ISSUE TITLE
brand_id: Integrity constraint violation

### ISSUE THREAD

**Issue by SpurnyMarek** [tiipiik/oc-catalog#21]
Hi, I got this error in the plugin.
An error occurred when I wanted to save a product and had not set up a brand.

![image](https://user-images.githubusercontent.com/43445347/72832343-f9a65a80-3c84-11ea-8882-967293904c0b.png)

**Comment by tiipiik** [comment]
Hello,
I will fix that. For now you can create a default brand and it will apply to all products automatically.

**Comment by tiipiik** [comment]
Fixed
