### ISSUE TITLE
No ability to remove or rearrange featured images?

### ISSUE THREAD

**Issue by ASM-Development** [tiipiik/oc-catalog#6]
No ability to remove or rearrange featured images? Why?
I used Backend\FormWidgets\FileUpload in fields.yaml and there was this feature.

**Comment by ASM-Development** [comment]
found, that right sidebar width of 300px hides buttons remove/rearrange

**Comment by tiipiik** [comment]
Yeah it's a mess, I hope this will be fix soon.
