### ISSUE TITLE
Ability to import/export with additional columns

### ISSUE THREAD

**Issue by ASM-Development** [tiipiik/oc-catalog#7]
We need ability to import/export products with custom fields and categories list

I guess it can be separate files: one for categories and hierarchy, second for products (like now), next for categories-product relations, and next for customfields-product relations... right?

At least now i forced to import products list and then manually select groups with fields, categories for them...and manually edit each of products to refill custom fields :'(

**Comment by tiipiik** [comment]
Import/export as it is was a first step as it provides a simple import option, but like you say it's not complete. I need time to make this, as it's a really more complicated feature (but whould be usefull I totally agree)
